---
name: CI
on:
  push:
    branches: [master]
    tags: ['*']
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
  cancel-in-progress: true
env:
  RUST_BACKTRACE: 1
  RUST_VERSION: 1.98.1
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Init
        run: ./ci/init.sh
      - name: Install Rust
        run: ./ci/rust.sh
      - name: Test
        run: ./ci/test.sh
